version: '3.8'

services:
  test_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/allure-results  # Persist allure results to host directory
    environment:
      - GITHUB_REPO=https://github.com/ShreyuKiBhuvi/SamplePythonSeleniumAutomationFramework.git
    command: ["pytest", "--html=report.html", "--alluredir=allure-results"]  # Overriding CMD if necessary
